#!/bin/bash

java -jar tools/closure-compiler.jar --language_in ECMASCRIPT5_STRICT \
                                     --compilation_level ADVANCED \
                                     --warning_level VERBOSE \
                                     $(for f in externs/*; \
                                     do echo "--externs $f"; done) \
                                     $(java -jar tools/sorter.jar $1)